### ISSUE TITLE
Add VS 2017 Support

### ISSUE THREAD

**Issue by petedavis** [Lombiq/Lombiq-Orchard-Visual-Studio-Extension#2]
Just rebuilt my laptop with VS2017 only and can no longer use this plugin.

**Comment by Piedone** [comment]
We'll do this as soon as we have some time. But if you know how to do the upgrade while keeping VS 2015 compatibility feel free to submit a PR :-).

**Comment by BenedekFarkas** [comment]
Fixed in [version 1.2.2](https://marketplace.visualstudio.com/items?itemName=LombiqVisualStudioExtension.LombiqOrchardVisualStudioExtension).
