### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [Lombiq/Lombiq-Orchard-Visual-Studio-Extension#4]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by Piedone** [comment]
Hi TJ,

thanks for your offer, we'd be glad to see what you'd do.

BTW in the meantime we've updated our company logo to this one:

![lombiq symbol logo color square](https://user-images.githubusercontent.com/1976647/40235171-b38a572c-5aa9-11e8-8a54-10640a0cf5a0.png)

Best,

Zoltán

**Comment by tjulises** [comment]
Hey again @Piedone ,
this is my first proposal
I hope you like it
If you have any suggestion, I'd like to know about it!
![logotipo lombiq 2018](https://user-images.githubusercontent.com/39039587/40582329-d4264a5c-6140-11e8-8b58-9b1ad1712ba0.png)

**Comment by Piedone** [comment]
Thank you @tjulises ! There's a bit of misunderstanding, as we're not looking for a new company logo. Our company is called Lombiq, what I've added above is our company logo; this VS extensions of ours, called just "Lombiq Orchard Visual Studio Extension", is one of our open source projects, and it could use a logo of its own. I'm sorry to tell that because you've obviously put a lot of efforts into these.

Out of curiosity, what do the letters in the circles of the first version mean?

**Comment by tjulises** [comment]
Hello @Piedone ,
I apologyze for my mistake,
I've come up with something new
![1](https://user-images.githubusercontent.com/39039587/40706481-f683839e-63bb-11e8-9ef8-0210b80b16f6.png)

**Comment by Piedone** [comment]
These look quite cool TJ! Would it be possible to include the Lombiq name and/or branding into it somehow?

**Comment by Piedone** [comment]
I think just adding the word Lombiq in front of "Orchard Visual Studio Extension" (since that's the full name of the project) and using the colors of the logo I've attached above would be good.

**Comment by tjulises** [comment]
Hi @Piedone  
I've come up with something new
If you like any of these logos, I can change the color or remove the letters if necessary. 
![2](https://user-images.githubusercontent.com/39039587/40817419-52143a36-6520-11e8-9355-dcec0b3a8e21.png)

**Comment by Piedone** [comment]
I think the previous versions were fine already :). Just with some reference to Lombiq. So maybe the "flat" versions of left second or right fourth from the previous batch with the new text?

I.e. these: 
![image](https://user-images.githubusercontent.com/1976647/40836562-69b79a12-6597-11e8-8893-413c3f744805.png)

**Comment by tjulises** [comment]
Ok I agree, could you give me an example on how to reference it to lombiq, could it be just by adding the name to the typography? @Piedone

**Comment by Piedone** [comment]
I mean basically the typo you used on the last batch that has "Lombiq" in it.

**Comment by tjulises** [comment]
![1234](https://user-images.githubusercontent.com/39039587/40882733-2e434c74-66b9-11e8-8951-25c0a72857b5.png)
hi @Piedone  ,
here i have updated the logo, I hope you like it.

**Comment by Piedone** [comment]
Thank you TJ, #2 and #4 look great!

**Comment by tjulises** [comment]
Which one shuould i submit in a pull request @Piedone  ? I personally like the #4 better

**Comment by Piedone** [comment]
Let's go with that!

**Comment by tjulises** [comment]
Great @piedone , I'll let you know when the pull request has been made!

**Comment by tjulises** [comment]
I've sended the pull request just now @Piedone 

I've sended the google drive link also for any update, I'll close this issue now, it's been a pleasure.

Best Regards.
-TJ.
